// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace RockstarResume.DAL.Migrations
{
    [DbContext(typeof(RockstarResumeContext))]
    [Migration("20190814120439_Third")]
    partial class Third
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RockstarResume.Model.AccountManager", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Birthay");

                    b.Property<string>("EmailAddress");

                    b.Property<string>("FirstName");

                    b.Property<string>("PhoneNumber");

                    b.Property<int>("Region");

                    b.Property<string>("Surname");

                    b.HasKey("Id");

                    b.ToTable("AccountManagers");
                });

            modelBuilder.Entity("RockstarResume.Model.Resume", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AccountManagerId");

                    b.Property<int>("Language");

                    b.Property<int?>("RockstarId");

                    b.HasKey("Id");

                    b.HasIndex("AccountManagerId");

                    b.HasIndex("RockstarId");

                    b.ToTable("Resumes");
                });

            modelBuilder.Entity("RockstarResume.Model.Rockstar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Birthay");

                    b.Property<bool>("DriversLicense");

                    b.Property<string>("EmailAddress");

                    b.Property<string>("FirstName");

                    b.Property<string>("Nationality");

                    b.Property<string>("PhoneNumber");

                    b.Property<string>("PictureUrl");

                    b.Property<int>("Region");

                    b.Property<string>("Surname");

                    b.HasKey("Id");

                    b.ToTable("Rockstars");
                });

            modelBuilder.Entity("RockstarResume.Model.RockstarProperties.RockstarProperty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<int?>("RockstarId");

                    b.HasKey("Id");

                    b.HasIndex("RockstarId");

                    b.ToTable("RockstarProperty");

                    b.HasDiscriminator<string>("Discriminator").HasValue("RockstarProperty");
                });

            modelBuilder.Entity("RockstarResume.Model.RockstarProperties.Certificate", b =>
                {
                    b.HasBaseType("RockstarResume.Model.RockstarProperties.RockstarProperty");

                    b.HasDiscriminator().HasValue("Certificate");
                });

            modelBuilder.Entity("RockstarResume.Model.RockstarProperties.Competence", b =>
                {
                    b.HasBaseType("RockstarResume.Model.RockstarProperties.RockstarProperty");

                    b.HasDiscriminator().HasValue("Competence");
                });

            modelBuilder.Entity("RockstarResume.Model.RockstarProperties.Education", b =>
                {
                    b.HasBaseType("RockstarResume.Model.RockstarProperties.RockstarProperty");

                    b.HasDiscriminator().HasValue("Education");
                });

            modelBuilder.Entity("RockstarResume.Model.RockstarProperties.Project", b =>
                {
                    b.HasBaseType("RockstarResume.Model.RockstarProperties.RockstarProperty");

                    b.HasDiscriminator().HasValue("Project");
                });

            modelBuilder.Entity("RockstarResume.Model.Resume", b =>
                {
                    b.HasOne("RockstarResume.Model.AccountManager", "AccountManager")
                        .WithMany()
                        .HasForeignKey("AccountManagerId");

                    b.HasOne("RockstarResume.Model.Rockstar", "Rockstar")
                        .WithMany()
                        .HasForeignKey("RockstarId");
                });

            modelBuilder.Entity("RockstarResume.Model.RockstarProperties.RockstarProperty", b =>
                {
                    b.HasOne("RockstarResume.Model.Rockstar", "Rockstar")
                        .WithMany("Properties")
                        .HasForeignKey("RockstarId");
                });
#pragma warning restore 612, 618
        }
    }
}
